////////////////////////////////////////////////////////////////////////////////
/// @file
/// @brief The Log_entry struct, representing an entry into the Log object.
////////////////////////////////////////////////////////////////////////////////
#ifndef EXSEIS_UTILS_LOGGING_LOG_ENTRY_HH
#define EXSEIS_UTILS_LOGGING_LOG_ENTRY_HH

#include "exseis/utils/logging/Source_position.hh"
#include "exseis/utils/logging/Status.hh"
#include "exseis/utils/logging/Verbosity.hh"

#include <string>


namespace exseis {
inline namespace utils {
inline namespace logging {


/// @brief An Log_entry instance is a discrete object generated by a
///        recording event and added to the logging list.
struct Log_entry {
    /// The status of the entry, e.g. Warning, Error, Note etc.
    Status status;

    /// The message for the end-user which is associated with the entry.
    std::string message;

    /// The level of verbosity the entry should be displayed at.
    Verbosity verbosity;

    /// The position in the source the entry was created.
    Source_position source_position;
};


}  // namespace logging
}  // namespace utils
}  // namespace exseis

#endif  // EXSEIS_UTILS_LOGGING_LOG_ENTRY_HH
