image: ubuntu:20.04

variables:
    # Needed to avoid blocking prompt during apt-get install from tzdata
    DEBIAN_FRONTEND: noninteractive

before_script:
    - time apt-get update
    - time apt-get install -y
        cmake
        doxygen graphviz
        gcc-8 g++-8
        git
        clang-9
        clang-tidy-9
        mpich


.snippets:
    - &configure
        mkdir build
        && pushd build
        && (
            set -x;
            time cmake
            -DCMAKE_VERBOSE_MAKEFILE=ON
            -DCMAKE_C_COMPILER=${CC}
            -DCMAKE_CXX_COMPILER=${CXX}
            -DCMAKE_CXX_EXTENSIONS=OFF
            -DCMAKE_C_EXTENSIONS=OFF
            -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
            -DBUILD_SHARED_LIBS=${BUILD_SHARED_LIBS}
            -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
            -DEXSEISDAT_ENABLE_DEVELOPMENT_FLAGS=${EXSEISDAT_ENABLE_DEVELOPMENT_FLAGS}
            -DEXSEISDAT_TEST_ENABLE_CMAKE_TESTS=ON
            -DEXSEISDAT_BUILD_DOCUMENTATION=${EXSEISDAT_BUILD_DOCUMENTATION}
            ..
        )
        && popd
    - &build
        time make -C build
    - &test
        time make -C build test ARGS=-V


.default_job: &default_job
    tags:
        - docker
    script:
        - *configure
        - *build
        - *test

.environment_variables:
    default_environment_variables: &default_environment_variables
        ASAN_OPTIONS: detect_leaks=0:detect_odr_violation=1

.flags:
    default_cmake_options: &default_cmake_options
        BUILD_SHARED_LIBS: "ON"
        CMAKE_BUILD_TYPE: Debug
        EXSEISDAT_ENABLE_DEVELOPMENT_FLAGS: "ON"
        EXSEISDAT_BUILD_DOCUMENTATION: "OFF"

stages:
    - static analysis
    - gcc debug test
    - clang debug test

.static_analysis_rules: &static_analysis_rules
    except:
        variables:
            - $CI_COMMIT_MESSAGE =~ /\[skip static ci\]/

Clang Format:
    <<: *static_analysis_rules
    <<: *default_job
    stage: static analysis
    before_script:
        - apt-get update && apt-get -y install git
    script:
        - ./scripts/run_format.sh --install-deps
            && git status
            && git diff-index --quiet HEAD
            || { echo "This commit contains unformatted files! Run scripts/run_format.sh on the project to format them correctly."; false; }

Clang Tidy:
    <<: *static_analysis_rules
    <<: *default_job
    stage: static analysis
    variables:
        <<: *default_environment_variables
        <<: *default_cmake_options
        CC: clang-9
        CXX: clang++-9
        CLANG_TIDY_EXECUTABLE: clang-tidy-9
    script:
        - *configure
        - ./scripts/run_lint.sh build

Doxygen:
    <<: *static_analysis_rules
    <<: *default_job
    stage: static analysis
    variables:
        <<: *default_environment_variables
        <<: *default_cmake_options
        CC: clang-9
        CXX: clang++-9
        EXSEISDAT_BUILD_DOCUMENTATION: "ON"
    # Doxygen in 20.04 currently version 1.8.17 is broken for "virtual void"
    image: ubuntu:18.04
    script:
        - *configure
        - make -C build/doc

Gcc Debug Test:
    <<: *default_job
    stage: gcc debug test
    variables:
        <<: *default_environment_variables
        <<: *default_cmake_options
        CC: gcc-8
        CXX: g++-8

Clang Debug Test: &clang_debug_test
    <<: *default_job
    stage: clang debug test
    variables:
        <<: *default_environment_variables
        <<: *default_cmake_options
        CC: clang-9
        CXX: clang++-9
