image: ubuntu:18.04

before_script:
    - apt-get update
    - apt-get install -y
        cmake
        doxygen graphviz
        gcc-8 g++-8
        git
        clang
        clang-tidy clang-format
        libfftw3-dev
        mpich


.snippets:
    - &configure
        mkdir build
        && pushd build
        && (
            set -x;
            cmake
            -DCMAKE_VERBOSE_MAKEFILE=ON
            -DCMAKE_C_COMPILER=${CC}
            -DCMAKE_CXX_COMPILER=${CXX}
            -DCMAKE_CXX_EXTENSIONS=OFF
            -DCMAKE_C_EXTENSIONS=OFF
            -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
            -DBUILD_SHARED_LIBS=${BUILD_SHARED_LIBS}
            -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
            -DEXSEISDAT_ENABLE_DEVELOPMENT_FLAGS=${EXSEISDAT_ENABLE_DEVELOPMENT_FLAGS}
            -DEXSEISDAT_TEST_ENABLE_CMAKE_TESTS=ON
            ..
        )
        && popd
    - &build
        make -C build
    - &test
        make -C build test ARGS=-V


.default_job: &default_job
    tags:
        - docker
    script:
        - *configure
        - *build
        - *test

.environment_variables:
    default_environment_variables: &default_environment_variables
        ASAN_OPTIONS: detect_leaks=0:detect_odr_violation=1

.flags:
    default_cmake_options: &default_cmake_options
        BUILD_SHARED_LIBS: "ON"
        CMAKE_BUILD_TYPE: Debug
        EXSEISDAT_ENABLE_DEVELOPMENT_FLAGS: "ON"

stages:
    - static analysis
    - gcc debug test
    - clang debug test

Clang Format:
    <<: *default_job
    stage: static analysis
    variables:
        <<: *default_environment_variables
        <<: *default_cmake_options
        CC: clang
        CXX: clang++
    image: ubuntu:19.04
    before_script:
        - apt-get update
        - apt-get install -y git clang-format-8
        - update-alternatives
            --install /usr/bin/clang-format clang-format
                      /usr/bin/clang-format-8 1
    script:
        - ./scripts/run_format.sh
            && git status
            && git diff-index --quiet HEAD
            || { echo "This commit contains unformatted files! Run scripts/run_format.sh on the project to format them correctly."; false; }

Clang Tidy:
    <<: *default_job
    stage: static analysis
    variables:
        <<: *default_environment_variables
        <<: *default_cmake_options
        CC: clang
        CXX: clang++
    script:
        - *configure
        - make -C build/test unpack_googletest
        - ./scripts/run_lint.sh build

Doxygen:
    <<: *default_job
    stage: static analysis
    variables:
        <<: *default_environment_variables
        <<: *default_cmake_options
        CC: clang
        CXX: clang++
    script:
        - *configure
        - make -C build/doc

Gcc Debug Test:
    <<: *default_job
    stage: gcc debug test
    variables:
        <<: *default_environment_variables
        <<: *default_cmake_options
        CC: gcc-8
        CXX: g++-8

Clang Debug Test: &clang_debug_test
    <<: *default_job
    stage: clang debug test
    variables:
        <<: *default_environment_variables
        <<: *default_cmake_options
        CC: clang
        CXX: clang++
