#!/bin/bash
#PBS -l nodes=1:ppn=24
#PBS -l walltime=0:04:00:00
#PBS -N systest
#PBS -A lero
#PBS -r n
#PBS -j oe
#PBS -m bea

cd $PBS_O_WORKDIR

source ../mod_intel
module load darshan/gcc/3.0.1-preload
export DARSHAN_LOG_PATH=$PBS_O_WORKDIR
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/ichec/home/staff/cathal/cathal/ExSeisDat/lib
time mpirun -ppn 24 ./systest 3 dat10/4D_REPEAT_LINES_2013_ALL_PRE-MIG_GATHERS.SEGY dat10/test.segy

