
all:
	(cd block; make)
	(cd object; make)
	(cd file; make)
	(cd ops; make)
	(cd set; make)
	(cd test; make)

clean:
	(cd block; make clean)
	(cd object; make clean)
	(cd file; make clean)
	(cd ops; make clean)
	(cd set; make clean)
	(cd test; make clean)

