
all:
	(cd anc; $(MAKE))
	(cd data; $(MAKE))
	(cd object; $(MAKE))
	(cd file; $(MAKE))
	(cd share; $(MAKE))

clean:
	(cd anc; $(MAKE) clean)
	(cd data; $(MAKE) clean)
	(cd object; $(MAKE) clean)
	(cd file; $(MAKE) clean)
	(cd share; $(MAKE) clean)

